services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: iot_database
    volumes:
      - pgdata:/var/lib/postgresql/data

  processor:
    build: .
    depends_on:
      - db
    environment:
      - MQTT_HOST=${EXTERNAL_MQTT_HOST}
      - MQTT_PORT=${EXTERNAL_MQTT_PORT}
      - MQTT_USER=${EXTERNAL_MQTT_USER}
      - MQTT_PASS=${EXTERNAL_MQTT_PASS}
      - DB_CONNECTION_STRING=Host=db;Database=iot_database;Username=${DB_USER};Password=${DB_PASSWORD}

volumes:
  pgdata:
